"""esquema inicial: notifications

Revision ID: 8d1f8ddc4f41
Revises: 
Create Date: 2026-08-06 22:21:09.744767

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d1f8ddc4f41'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=191), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=191), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_micros', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_reference', 'notifications', ['reference'], unique=False)
    op.create_index('ix_notifications_tenant', 'notifications', ['app_id', 'business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_tenant', table_name='notifications')
    op.drop_index('ix_notifications_reference', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
